name: CI

on:
  push:
    branches: ['master', 'develop']
  pull_request:
    branches: ['master', 'develop']

permissions:
  actions: read
  contents: write
  packages: write

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          # Setup NPM authentication
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # Run tests and generate coverage
      - run: yarn nx affected -t lint test build

      # Upload test coverage to CodeClimate
      - name: Upload coverage to Code Climate
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/libs/jsonapi/lcov.info:lcov
            ${{github.workspace}}/coverage/libs/jsonapi/angular/lcov.info:lcov
