name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: write
  packages: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          # Setup NPM authentication
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4
      - run: yarn nx affected -t lint test build

      # Publish packages when pushing to main
      - name: Publish to NPM
        if: github.ref == 'refs/heads/main'
        run: yarn nx affected -t nx-release-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
